export const models = [
  {
    modelId: "eleven_v3",
    name: "Eleven v3 (alpha)",
    canBeFinetuned: false,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "The most expressive model. Supports 70+ languages. Requires more prompt engineering than our previous models. In alpha and the reliability will improve over time.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 3000,
    maxCharactersRequestSubscribedUser: 3000,
    maximumTextLengthPerRequest: 3000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard",
  },
  {
    modelId: "eleven_multilingual_v2",
    name: "Eleven Multilingual v2",
    canBeFinetuned: true,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: true,
    canUseSpeakerBoost: true,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our most life-like, emotionally rich mode in 29 languages. Best for voice overs, audiobooks, post-production, or any other content creation needs.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 10000,
    maxCharactersRequestSubscribedUser: 10000,
    maximumTextLengthPerRequest: 10000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard",
  },
  {
    modelId: "eleven_flash_v2_5",
    name: "Eleven Flash v2.5",
    canBeFinetuned: true,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our ultra low latency model in 32 languages. Ideal for conversational use cases.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 40000,
    maxCharactersRequestSubscribedUser: 40000,
    maximumTextLengthPerRequest: 40000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 0.5 },
    concurrencyGroup: "turbo",
  },
  {
    modelId: "eleven_turbo_v2_5",
    name: "Eleven Turbo v2.5",
    canBeFinetuned: true,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our high quality, low latency model in 32 languages. Best for developer use cases where speed matters and you need non-English languages.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 40000,
    maxCharactersRequestSubscribedUser: 40000,
    maximumTextLengthPerRequest: 40000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 0.5 },
    concurrencyGroup: "turbo",
  },
  {
    modelId: "eleven_turbo_v2",
    name: "Eleven Turbo v2",
    canBeFinetuned: true,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our English-only, low latency model. Best for developer use cases where speed matters and you only need English. Performance is on par with Turbo v2.5.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 30000,
    maxCharactersRequestSubscribedUser: 30000,
    maximumTextLengthPerRequest: 30000,
    languages: [[Object]],
    modelRates: { characterCostMultiplier: 0.5 },
    concurrencyGroup: "turbo",
  },
  {
    modelId: "eleven_flash_v2",
    name: "Eleven Flash v2",
    canBeFinetuned: true,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our ultra low latency model in english. Ideal for conversational use cases.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 30000,
    maxCharactersRequestSubscribedUser: 30000,
    maximumTextLengthPerRequest: 30000,
    languages: [[Object]],
    modelRates: { characterCostMultiplier: 0.5 },
    concurrencyGroup: "turbo",
  },
  {
    modelId: "eleven_multilingual_v1",
    name: "Eleven Multilingual v1",
    canBeFinetuned: false,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our first Multilingual model, capability of generating speech in 10 languages. Now outclassed by Multilingual v2 (for content creation) and Turbo v2.5 (for low latency use cases).",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 10000,
    maxCharactersRequestSubscribedUser: 10000,
    maximumTextLengthPerRequest: 10000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard",
  },
  {
    modelId: "eleven_multilingual_sts_v2",
    name: "Eleven Multilingual v2",
    canBeFinetuned: true,
    canDoTextToSpeech: false,
    canDoVoiceConversion: true,
    canUseStyle: true,
    canUseSpeakerBoost: true,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our cutting-edge, multilingual speech-to-speech model is designed for situations that demand unparalleled control over both the content and the prosody of the generated speech across various languages.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 10000,
    maxCharactersRequestSubscribedUser: 10000,
    maximumTextLengthPerRequest: 10000,
    languages: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard_eleven_multilingual_sts_v2",
  },
  {
    modelId: "eleven_monolingual_v1",
    name: "Eleven English v1",
    canBeFinetuned: false,
    canDoTextToSpeech: true,
    canDoVoiceConversion: false,
    canUseStyle: false,
    canUseSpeakerBoost: false,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our first ever text to speech model. Now outclassed by Multilingual v2 (for content creation) and Turbo v2.5 (for low latency use cases).",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 10000,
    maxCharactersRequestSubscribedUser: 10000,
    maximumTextLengthPerRequest: 10000,
    languages: [[Object]],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard",
  },
  {
    modelId: "eleven_english_sts_v2",
    name: "Eleven English v2",
    canBeFinetuned: false,
    canDoTextToSpeech: false,
    canDoVoiceConversion: true,
    canUseStyle: true,
    canUseSpeakerBoost: true,
    servesProVoices: false,
    tokenCostFactor: 1,
    description:
      "Our state-of-the-art speech to speech model suitable for scenarios where you need maximum control over the content and prosody of your generations.",
    requiresAlphaAccess: false,
    maxCharactersRequestFreeUser: 5000,
    maxCharactersRequestSubscribedUser: 5000,
    maximumTextLengthPerRequest: 5000,
    languages: [[Object]],
    modelRates: { characterCostMultiplier: 1 },
    concurrencyGroup: "standard_eleven_english_sts_v2",
  },
];
