export const voices = [
  {
    voiceId: "21m00Tcm4TlvDq8ikWAM",
    name: "Rachel",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Matter-of-fact, personable woman. Great for conversational use cases.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/b4928a68-c03b-411f-8533-3d5c299fd451.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [],
    verifiedLanguages: [],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "2EiwWnXFnvU5JabPnv8n",
    name: "Clyde",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Great for character use-cases",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/2EiwWnXFnvU5JabPnv8n/65d80f52-703f-4cae-a91d-75d4e200ed02.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "CwhRBWXzGAHq8TQ4Fs17",
    name: "Roger",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Easy going and perfect for casual conversations.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "EXAVITQu4vr4xnSDxMaL",
    name: "Sarah",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Young adult woman with a confident and warm, mature quality and a reassuring, professional tone.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "FGY2WhTYpPnrIDTdsKH5",
    name: "Laura",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "This young adult female voice delivers sunny enthusiasm with a quirky attitude.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67341759-ad08-41a5-be6e-de12fe448618.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "GBv7mTt0atIp3Br8iCZE",
    name: "Thomas",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Soft and subdued male voice, optimal for narrations or meditations",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/GBv7mTt0atIp3Br8iCZE/98542988-5267-4148-9a9e-baa8c4f14644.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "IKne3meq5aSn9XLyUdCD",
    name: "Charlie",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A young Australian male with a confident and energetic voice.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "JBFqnCBsd6RMkjVDRZzb",
    name: "George",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Warm resonance that instantly captivates listeners.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "N2lVS1w4EtoT3dr4eOWO",
    name: "Callum",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Deceptively gravelly, yet unsettling edge.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "SAz9YHcvj6GT2YYXdXww",
    name: "River",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A relaxed, neutral voice ready for narrations or conversational projects.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/SAz9YHcvj6GT2YYXdXww/e6c95f0b-2227-491a-b3d7-2249240decb7.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "SOYHLrjzK2X1ezoPC6cr",
    name: "Harry",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "An animated warrior ready to charge forward.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/SOYHLrjzK2X1ezoPC6cr/86d178f6-f4b6-4e0e-85be-3de19f490794.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "TX3LPaxmHKxFdv7VOQHJ",
    name: "Liam",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A young adult with energy and warmth - suitable for reels and shorts.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "Xb7hH8MSUJpSbSDYk0k2",
    name: "Alice",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Clear and engaging, friendly woman with a British accent suitable for e-learning.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "XrExE9yKIg1WjnnlVkGX",
    name: "Matilda",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A professional woman with a pleasing alto pitch. Suitable for many use cases.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "bIHbv24MWmeRgasZH58o",
    name: "Will",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Conversational and laid back.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "cgSgspJ2msm6clMCkdW9",
    name: "Jessica",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Young and popular, this playful American female voice is perfect for trendy content.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "cjVigY5qzO86Huf0OWal",
    name: "Eric",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A smooth tenor pitch from a man in his 40s - perfect for agentic use cases.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "iP95p4xoKVk53GoZ742B",
    name: "Chris",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Natural and real, this down-to-earth voice is great across many use-cases.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "nPczCjzI2devNBz1zQrb",
    name: "Brian",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Middle-aged man with a resonant and comforting tone. Great for narrations and advertisements.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "onwK4e9ZLuTAKqWW03F9",
    name: "Daniel",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A strong voice perfect for delivering a professional broadcast or news story.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "pFZP5JQG7iQjIQuC4Bku",
    name: "Lily",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description:
      "Velvety British female voice delivers news and narrations with warmth and clarity.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "pqHfZKP75CvOlQylNhV4",
    name: "Bill",
    samples: undefined,
    category: "premade",
    fineTuning: [Object],
    labels: [Object],
    description: "Friendly and comforting voice ready to narrate your stories.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: undefined,
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [Array],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: undefined,
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: undefined,
  },
  {
    voiceId: "fUjY9K2nAIwlALOwSiwc",
    name: "Yui - Japanese female Anime voice",
    samples: undefined,
    category: "professional",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A bright and cute, soothing voice. Japanese female. Perfect for Anime, VTubers, games, and storytelling.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/database/user/L1GYYljlF1PEq09aUQgwwlh7DJm1/voices/fUjY9K2nAIwlALOwSiwc/C79oVJJJuCSBWmwsTJYV.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: [Object],
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: "admin",
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: 1758872449,
  },
  {
    voiceId: "GxxMAMfQkDlnqjpzjLHH",
    name: "Kozy (Male Japanese Narrative Voice - Tokyo Standard Accent)",
    samples: undefined,
    category: "professional",
    fineTuning: [Object],
    labels: [Object],
    description:
      "A Japanese male voice. 20s - 30s. Perfect for corporate presentations, audiobooks and any type of narrations.",
    previewUrl:
      "https://storage.googleapis.com/eleven-public-prod/custom/voices/GxxMAMfQkDlnqjpzjLHH/stpExeeeVw1cHI9MxLrT.mp3",
    availableForTiers: [],
    settings: undefined,
    sharing: [Object],
    highQualityBaseModelIds: [Array],
    verifiedLanguages: [],
    safetyControl: undefined,
    voiceVerification: [Object],
    permissionOnResource: "admin",
    isOwner: false,
    isLegacy: false,
    isMixed: false,
    favoritedAtUnix: undefined,
    createdAtUnix: 1758873022,
  },
];
